steps:
  - id: "Create dataflow template"
    name: 'gcr.io/gcpproject-380209/dataflow-python3:latest'
    entrypoint: 'python'
    args: [ '-m', 'main',
         "--job_name=wordtestcount",
         "--project=gcpproject-380209", 
         "--region=us-central1",
         "--template_location=gs://gcp-demobucket/templates/Template_Test/",
         "--staging_location=gs://gcp-demobucket/staging/",
         "--temp_location=gs://gcp-demobucket/tmp/",
         "--runner=DataflowRunner",
         "--setup_file='./setup.py'",
         "--autoscaling_algorithm=NONE"
         ]
    waitFor: [
      'Activate virtual environment venv'
      ]
